name: GitHub Actions Demo
on:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.1"
      - run: yarn install
      - run: yarn run test
